### ISSUE TITLE
Executable of some sort for desktop apps

### ISSUE THREAD

**Issue by Dune808** [OvalQuilter/lyrics-status#13]
Would it be possible to make a version for the desktop apps? I find that even going to a different tab in my browser basically negates the functionality of lyrics-status, making it a slightly annoying issue to use any other app/tab. Would be nice to have a plugin or something similar to get better results when generally using your computer

**Comment by OvalQuilter** [comment]
Hello! I already tried to make it work without a browser, no luck. Maybe in the future I'll return to this initiative or even make an executable if I'll have enough time, but for now we have what we have.

**Comment by sealldeveloper** [comment]
> Hello! I already tried to make it work without a browser, no luck. Maybe in the future I'll return to this initiative or even make an executable if I'll have enough time, but for now we have what we have.

Gday, was wondering if you could do this with something like Selenium or Puppeteer?
