### ISSUE TITLE
Endlessly fetching everything

### ISSUE THREAD

**Issue by Dune808** [OvalQuilter/lyrics-status#14]
![image_2024-05-31_220547108](https://github.com/OvalQuilter/lyrics-status/assets/146230115/90713339-3c5a-4118-9a90-81afbf074037)
Kinda speaks for itself

**Comment by FFounddd** [comment]
Same problem here, how ever I don't think this issue is going to be fixed as Oval hasn't updated this since March 29th of last year. Been looking for a fix but can't find anything.

**Comment by OvalQuilter** [comment]
Hello! Spotify has made lyrics available only for Premium subscription users; if you open lyrics tab, you'll see __(if you don't have Premium ofc)__. I can't avoid this.
Okay, that's the main thing.
Currently, the script won't work even if you have Premium, I'll fix that.

**Comment by Dune808** [comment]
Sweet, sounds great! This was by far one of my most favorite scripts and seeing it being worked on again is amazing, thank you kindly good sir! If you need any testers I am far and away happy to help.

**Comment by FFounddd** [comment]
Really glad to hear it's being worked on too! I love having my lyrics in my status 😋

**Comment by OvalQuilter** [comment]
So I've updated the script. Can you please test it? If something is not working as intended just send me debug info: `Debug` tab -> `Copy debug info`
Thanks.

**Comment by SirLeonNice** [comment]
> So I've updated the script. Can you please test it? If something is not working as intended just send me debug info: `Debug` tab -> `Copy debug info` Thanks.

Hey, it wont work for me sadly. I'm using tampermonkey and I'm unsure if the description is updated to. But I do have created the script a few minutes ago after you've updated it. Here are the Debug infos 

`{"trackName":"FLIGHTMODE","trackAuthor":"absent","trackId":"5QR4nzCcZapRSyGVHPEIWT","oldTrackId":"4dBvzTrVgH5q39xSgOjE7m","trackDuration":156000,"trackProgress":13010,"lyrics":[],"lyricsFullRes":{},"currentLyrics":null,"hasLyrics":false,"isPlaying":true}`

**Comment by FFounddd** [comment]
> So I've updated the script. Can you please test it? If something is not working as intended just send me debug info: `Debug` tab -> `Copy debug info` Thanks.

Thought you might want multiple debugs, mines the same as Leons one though so idk how much it'll help

`{"trackName":"Drones","trackAuthor":"Rise Against","trackId":"7wOYlhUoHMpg2r96VWiIYR","oldTrackId":null,"trackDuration":181600,"trackProgress":30998,"lyrics":[],"lyricsFullRes":{},"currentLyrics":null,"hasLyrics":false,"isPlaying":true}`

**Comment by OvalQuilter** [comment]
I figured out that Spotify randomly fails script's requests to retrieve lyrics, but I found a workaround that should work for now.
Also, I figured that Spotify can sometimes say that lyrics for certain song don't exist. Maybe it's because the account doesn't have Premium.
I will be waiting for your feedback.

**Comment by OvalQuilter** [comment]
> > So I've updated the script. Can you please test it? If something is not working as intended just send me debug info: `Debug` tab -> `Copy debug info` Thanks.
> 
> Thought you might want multiple debugs, mines the same as Leons one though so idk how much it'll help
> 
> `{"trackName":"Drones","trackAuthor":"Rise Against","trackId":"7wOYlhUoHMpg2r96VWiIYR","oldTrackId":null,"trackDuration":181600,"trackProgress":30998,"lyrics":[],"lyricsFullRes":{},"currentLyrics":null,"hasLyrics":false,"isPlaying":true}`

Like I said, I checked this song and it doesn't have lyrics.

**Comment by SirLeonNice** [comment]
> I figured out that Spotify randomly fails script's requests to retrieve lyrics, but I found a workaround that should work for now. Also, I figured that Spotify can sometimes say that lyrics for certain song don't exist. Maybe it's because the account doesn't have Premium. I will be waiting for your feedback.

I do got premium

**Comment by Dune808** [comment]
It does indeed work amazingly, thank you once again oval for making one of the best scripts I've ever used!
