### ISSUE TITLE
Doesn't work as of the latest update 2.1.1

### ISSUE THREAD

**Issue by aaashleyyyy** [OvalQuilter/lyrics-status#6]
I don't know what else to say. All the buttons work, the debug tab shows the lyrics, there's no signs of it being broken in the console (I think), it just doesn't send to my Discord profile.

But, some of the console log anyway.
![chrome_BgKtbV3Qpl](https://user-images.githubusercontent.com/83358470/199260912-2c9b3be5-2e34-478b-8c8b-aa57e15eaf32.png)

**Comment by YnwLNE** [comment]
Can second this with the same output

**Comment by OvalQuilter** [comment]
Hello! It seems to be a problem with Discord, as lyrics are displaying in Debug tab it's not problem with Spotify. Can you please open `Network` tab in devtools and look at requests? If there are any errors, please send me a screenshot.

**Comment by aaashleyyyy** [comment]
A few days later it started working again for seemly no reason, so, issue closed.
