### ISSUE TITLE
emojis

### ISSUE THREAD

**Issue by imnew827** [OvalQuilter/lyrics-status#7]
anyway to keep an emoji with  the status running?

**Comment by OvalQuilter** [comment]
It's not possible.
Or at least, it's not worked for me.

**Comment by aaashleyyyy** [comment]
> > It's not possible. Or at least, it's not worked for me.
> 
> I made a personal modification to the script so whenever the lyric is "♩ "it replaces it with "🎶 {song_name} 🎶" so it is possible.

Also just tried it, putting emojis in the custom status option works fine for me

**Comment by OvalQuilter** [comment]
> > > It's not possible. Or at least, it's not worked for me.
> > 
> > 
> > I made a personal modification to the script so whenever the lyric is "♩ "it replaces it with "notes {song_name} notes" so it is possible.
> 
> Also just tried it, putting emojis in the custom status option works fine for me

Maybe I misunderstand you, but about which emojis we are talking? I meant emoji before status: 
![image](https://user-images.githubusercontent.com/69106951/203173157-fbdf31c5-d508-47f5-8f16-cd1c9f2b0740.png)
not emoji in text.

**Comment by imnew827** [comment]
yeah i meant emoji before status too

**Comment by aaashleyyyy** [comment]
[](https://luna.gitlab.io/discord-unofficial-docs/custom_status.html#customstatus-structure)

I don't know if this helps, but, here's some extra documentation on statuses.

**Comment by OvalQuilter** [comment]
> https://luna.gitlab.io/discord-unofficial-docs/custom_status.html#customstatus-structure
> 
> I don't know if this helps, but, here's some extra documentation on statuses.

Hmm… Now it worked for me. Maybe I did something wrong, or it was a bug when I tried previous time. I'll add custom emoji feature in the next update.
Also, thanks for such documentation! Official Discord's docs not tells about some API requests and settings, so this may help me add some features to Lyrics Status.

**Comment by aaashleyyyy** [comment]
> > https://luna.gitlab.io/discord-unofficial-docs/custom_status.html#customstatus-structure
> > I don't know if this helps, but, here's some extra documentation on statuses.
> 
> Hmm… Now it worked for me. Maybe I did something wrong, or it was a bug when I tried previous time. I'll add custom emoji feature in the next update. Also, thanks for such documentation! Official Discord's docs not tells about some API requests and settings, so this may help me add some features to Lyrics Status.

Can you share the code of the API request you used to make emojis work?

**Comment by OvalQuilter** [comment]
> > > https://luna.gitlab.io/discord-unofficial-docs/custom_status.html#customstatus-structure
> > > I don't know if this helps, but, here's some extra documentation on statuses.
> > 
> > 
> > Hmm… Now it worked for me. Maybe I did something wrong, or it was a bug when I tried previous time. I'll add custom emoji feature in the next update. Also, thanks for such documentation! Official Discord's docs not tells about some API requests and settings, so this may help me add some features to Lyrics Status.
> 
> Can you share the code of the API request you used to make emojis work?

Haha, sorry, didn't see your message when closed the issue. 😅
If you still need the code, you can look at [this](https://github.com/OvalQuilter/lyrics-status/blob/f803182dfb078352544ff586107a90fb67b0dec0/LyricsStatus.js#L793) line, just change the value to a unicode emoji and you are good to go (if you're not using jQuery you need to make fetch or XMLHttpRequest request instead).

**Comment by imnew827** [comment]
can u push an update @OvalQuilter

**Comment by OvalQuilter** [comment]
> can u push an update @OvalQuilter

Sorry, but what you mean? I already released an update and you should already have it.
