### ISSUE TITLE
(Request) Filter Explicit Lyrics Out

### ISSUE THREAD

**Issue by Audomations** [OvalQuilter/lyrics-status#9]
Can you find a way to filter the Explicit words out of the status?

**Comment by Twelve0001** [comment]
Define explicit?

**Comment by Audomations** [comment]
Curse Words like ```f**k``` or ```sh*t```

**Comment by Twelve0001** [comment]
> Curse Words like ```f**k``` or ```sh*t```

add me on discord, Twelve#0001, i can make a custom version of the script for you that does that.

**Comment by Audomations** [comment]
ok ncdb#8430
